### ISSUE TITLE
Bookings - cost-related options

### ISSUE THREAD

**Issue by stringiest** [stringiest/new-callacon#11]
Add check boxes or input boxes for the following cost-related options:
- make booking cancellable for extra 15%?
- donations
- assistance fund claim - 50% discount, not available with single person supplement
- single person supplement - £50 per night, capped at £200 overall.
- dog - £30 per dog

Add cost field & description (long text?) for manual update by admin

**Comment by hopshackle** [comment]
To avoid hard-coding in too much fragility, the ability for an admin (me?) to update the amount owed with comments would be helpful.

For an MVP, just having the ability for a person to book specific dates with tick-boxes for single-person, dog, assistance fund etc. would be very useful. The workflow could then be for Callacon admin (me) add in the final details. I suppose the ley point is that if a record is amended (and admin will - I think - need to be able to do this), then an email goes to to the person concerned.

**Comment by stringiest** [comment]
Excellent ideas @hopshackle  - yes! 

So MVP mimics current sign-up process and user experience, but adds on automatic email confirmation of booking (and some kind of prompt for an admin to calculate amount payable?). System then sends email to booker if record is amended (when cost added).

Any cost-calculating, payment data uploading or balance calculating features could be v2.
